name: shadart
description: A clean, accessible, shadcn-inspired component library for Flutter.
homepage: https://github.com/jsondev-v2/shadart
repository: https://github.com/jsondev-v2/shadart
issue_tracker: https://github.com/jsondev-v2/shadart/issues
version: 0.1.1

topics:
  - ui
  - widgets
  - design-system
  - shadcn

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
